/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.laboratorio.view;

/**
 *
 * @author equipo 1
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    // Tarea #13: gráficas de series temporales (librería JFreeChart)
    private final GraficaTiempo graficaAnalogica
            = new GraficaTiempo("Voltaje (V)", -0.2, 5.2, false, new java.awt.Color(31, 95, 168));
    private final GraficaTiempo graficaDigital
            = new GraficaTiempo("Estado lógico", -0.2, 1.2, true, new java.awt.Color(192, 57, 43));

    public VentanaPrincipal() {
        initComponents();
        configurarGraficas();
    }

    /**
     * Tarea #13: ubica las dos gráficas en la ventana (arriba la analógica,
     * abajo la digital).
     *
     * NOTA para el diseño de la GUI: cuando se agregue en el Form Editor un
     * JPanel para las gráficas, reemplazar getContentPane() por ese panel.
     */
    private void configurarGraficas() {
       panelGraficaAnalogica.setLayout(new java.awt.BorderLayout());
        panelGraficaAnalogica.add(graficaAnalogica, java.awt.BorderLayout.CENTER);

        panelGraficaDigital.setLayout(new java.awt.BorderLayout());
        panelGraficaDigital.add(graficaDigital, java.awt.BorderLayout.CENTER);

        pack();   // ajusta el tamaño de la ventana
    }

    public GraficaTiempo getGraficaAnalogica() {
        return graficaAnalogica;
    }

    public GraficaTiempo getGraficaDigital() {
        return graficaDigital;
    }

        public javax.swing.JTextField getTxtMuestreo() {
        return txtMuestreo;
    }

    public javax.swing.JButton getBtnCambiarMuestreo() {
        return btnCambiarMuestreo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGraficaAnalogica = new javax.swing.JPanel();
        panelGraficaDigital = new javax.swing.JPanel();
        txtMuestreo = new javax.swing.JTextField();
        btnCambiarMuestreo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGraficaAnalogica.setBorder(javax.swing.BorderFactory.createTitledBorder("Señal analogica"));

        javax.swing.GroupLayout panelGraficaAnalogicaLayout = new javax.swing.GroupLayout(panelGraficaAnalogica);
        panelGraficaAnalogica.setLayout(panelGraficaAnalogicaLayout);
        panelGraficaAnalogicaLayout.setHorizontalGroup(
            panelGraficaAnalogicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        panelGraficaAnalogicaLayout.setVerticalGroup(
            panelGraficaAnalogicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        panelGraficaDigital.setBorder(javax.swing.BorderFactory.createTitledBorder("Señal digital"));

        javax.swing.GroupLayout panelGraficaDigitalLayout = new javax.swing.GroupLayout(panelGraficaDigital);
        panelGraficaDigital.setLayout(panelGraficaDigitalLayout);
        panelGraficaDigitalLayout.setHorizontalGroup(
            panelGraficaDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        panelGraficaDigitalLayout.setVerticalGroup(
            panelGraficaDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        txtMuestreo.setText("10");
        txtMuestreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Muestreo"));
        txtMuestreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMuestreoActionPerformed(evt);
            }
        });

        btnCambiarMuestreo.setText("Actualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCambiarMuestreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMuestreo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(panelGraficaAnalogica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelGraficaDigital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(panelGraficaAnalogica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMuestreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCambiarMuestreo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGraficaDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMuestreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMuestreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMuestreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarMuestreo;
    private javax.swing.JPanel panelGraficaAnalogica;
    private javax.swing.JPanel panelGraficaDigital;
    private javax.swing.JTextField txtMuestreo;
    // End of variables declaration//GEN-END:variables
}
